version: '3'
services:
  mysql_db:
    container_name: mysql_db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: secretword
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  signup-login:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
    - mysql_db